#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Pass_App.Resource", IsApplication=true)]

namespace Pass_App
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int MRU = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050034
			public const int EditSessionTutor = 2131034164;
			
			// aapt resource value: 0x7f050020
			public const int MainScreenLogoTextView = 2131034144;
			
			// aapt resource value: 0x7f05000b
			public const int SessionDate = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int SessionTime = 2131034125;
			
			// aapt resource value: 0x7f050033
			public const int ViewSessionTutor = 2131034163;
			
			// aapt resource value: 0x7f050050
			public const int WelcomeTutorTextView = 2131034192;
			
			// aapt resource value: 0x7f050035
			public const int acct2121 = 2131034165;
			
			// aapt resource value: 0x7f050036
			public const int acct3224 = 2131034166;
			
			// aapt resource value: 0x7f050032
			public const int address_label = 2131034162;
			
			// aapt resource value: 0x7f05003b
			public const int cancel = 2131034171;
			
			// aapt resource value: 0x7f05004d
			public const int confirmAttendance = 2131034189;
			
			// aapt resource value: 0x7f05001e
			public const int confirmLoginButton = 2131034142;
			
			// aapt resource value: 0x7f050042
			public const int confirmPassword = 2131034178;
			
			// aapt resource value: 0x7f050054
			public const int confirmSessionAttendanceButton = 2131034196;
			
			// aapt resource value: 0x7f05004f
			public const int contactSLC = 2131034191;
			
			// aapt resource value: 0x7f050055
			public const int contactSLCButton = 2131034197;
			
			// aapt resource value: 0x7f050023
			public const int courseName = 2131034147;
			
			// aapt resource value: 0x7f050052
			public const int createSessionButton = 2131034194;
			
			// aapt resource value: 0x7f050028
			public const int date = 2131034152;
			
			// aapt resource value: 0x7f05002f
			public const int dateDisplay = 2131034159;
			
			// aapt resource value: 0x7f05002e
			public const int dateHead = 2131034158;
			
			// aapt resource value: 0x7f05001b
			public const int description = 2131034139;
			
			// aapt resource value: 0x7f050025
			public const int dropButton = 2131034149;
			
			// aapt resource value: 0x7f05004b
			public const int editProfile = 2131034187;
			
			// aapt resource value: 0x7f050051
			public const int editProfileButton = 2131034193;
			
			// aapt resource value: 0x7f05003f
			public const int email = 2131034175;
			
			// aapt resource value: 0x7f05001d
			public const int emailInput = 2131034141;
			
			// aapt resource value: 0x7f05001c
			public const int emailPrompt = 2131034140;
			
			// aapt resource value: 0x7f05003d
			public const int firstName = 2131034173;
			
			// aapt resource value: 0x7f050014
			public const int firstNameInput = 2131034132;
			
			// aapt resource value: 0x7f050013
			public const int firstNamePrompt = 2131034131;
			
			// aapt resource value: 0x7f050037
			public const int fnce3227 = 2131034167;
			
			// aapt resource value: 0x7f05001f
			public const int forgotPasswordButton = 2131034143;
			
			// aapt resource value: 0x7f05000a
			public const int gridLayout1 = 2131034122;
			
			// aapt resource value: 0x7f050012
			public const int header = 2131034130;
			
			// aapt resource value: 0x7f05003e
			public const int lastName = 2131034174;
			
			// aapt resource value: 0x7f050016
			public const int lastNameInput = 2131034134;
			
			// aapt resource value: 0x7f050015
			public const int lastNamePrompt = 2131034133;
			
			// aapt resource value: 0x7f050011
			public const int location = 2131034129;
			
			// aapt resource value: 0x7f05002b
			public const int locationDisplay = 2131034155;
			
			// aapt resource value: 0x7f05002a
			public const int locationHead = 2131034154;
			
			// aapt resource value: 0x7f050021
			public const int loginButton = 2131034145;
			
			// aapt resource value: 0x7f050038
			public const int math1200 = 2131034168;
			
			// aapt resource value: 0x7f05000e
			public const int nextButton = 2131034126;
			
			// aapt resource value: 0x7f050029
			public const int notes = 2131034153;
			
			// aapt resource value: 0x7f05003a
			public const int ok = 2131034170;
			
			// aapt resource value: 0x7f050041
			public const int password = 2131034177;
			
			// aapt resource value: 0x7f05001a
			public const int passwordInput = 2131034138;
			
			// aapt resource value: 0x7f050019
			public const int passwordPrompt = 2131034137;
			
			// aapt resource value: 0x7f050031
			public const int projectedAttendanceDisplay = 2131034161;
			
			// aapt resource value: 0x7f050030
			public const int projectedAttendanceHead = 2131034160;
			
			// aapt resource value: 0x7f050039
			public const int psyc2210 = 2131034169;
			
			// aapt resource value: 0x7f050024
			public const int returnButton = 2131034148;
			
			// aapt resource value: 0x7f05000c
			public const int scrollView1 = 2131034124;
			
			// aapt resource value: 0x7f050010
			public const int sessionPlan = 2131034128;
			
			// aapt resource value: 0x7f05004c
			public const int sessionSignUp = 2131034188;
			
			// aapt resource value: 0x7f050022
			public const int signupButton = 2131034146;
			
			// aapt resource value: 0x7f050001
			public const int student1 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int student2 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int student3 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int student4 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int student5 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int student6 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int student7 = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int student8 = 2131034120;
			
			// aapt resource value: 0x7f050040
			public const int studentID = 2131034176;
			
			// aapt resource value: 0x7f050018
			public const int studentIDInput = 2131034136;
			
			// aapt resource value: 0x7f050017
			public const int studentIDPrompt = 2131034135;
			
			// aapt resource value: 0x7f05003c
			public const int submit = 2131034172;
			
			// aapt resource value: 0x7f050009
			public const int submitButton = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int textView1 = 2131034112;
			
			// aapt resource value: 0x7f05000f
			public const int textView2 = 2131034127;
			
			// aapt resource value: 0x7f050027
			public const int time = 2131034151;
			
			// aapt resource value: 0x7f05002d
			public const int timeDisplay = 2131034157;
			
			// aapt resource value: 0x7f05002c
			public const int timeHead = 2131034156;
			
			// aapt resource value: 0x7f050044
			public const int tutorCancel = 2131034180;
			
			// aapt resource value: 0x7f05004a
			public const int tutorConfirmPassword = 2131034186;
			
			// aapt resource value: 0x7f050047
			public const int tutorEmail = 2131034183;
			
			// aapt resource value: 0x7f050045
			public const int tutorFirstName = 2131034181;
			
			// aapt resource value: 0x7f050046
			public const int tutorLastName = 2131034182;
			
			// aapt resource value: 0x7f050026
			public const int tutorName = 2131034150;
			
			// aapt resource value: 0x7f050049
			public const int tutorPassword = 2131034185;
			
			// aapt resource value: 0x7f050048
			public const int tutorStudentID = 2131034184;
			
			// aapt resource value: 0x7f050043
			public const int tutorSubmit = 2131034179;
			
			// aapt resource value: 0x7f050053
			public const int viewEditSessionButton = 2131034195;
			
			// aapt resource value: 0x7f05004e
			public const int viewRegisteredSession = 2131034190;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ConfirmAttendance = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CreateSession1 = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CreateSession2 = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int EditSession = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int EditStudentProfile = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int EditTutorProfile = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Login = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Main = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int SessionDetailsStudent = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int SessionDetailsTutor = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int SessionSelectionTutor = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int SessionSignUp = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int SignUp = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int SignUpTutor = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int StudentLogin = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int TutorProfile = 2130903055;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
